### ISSUE TITLE
HTML charset

### ISSUE THREAD

**Issue by proweb** [JBZoo/JBlank#1]
В [init.php](https://github.com/smetdenis/jblank/blob/master/php/init.php#L60) имеем:

```
// set HTML5 mode (for <head> tag)
    ->html5(true)
```

Однако это ничего не дает.
Как у нас был charset в старом формате так он и остается:

![_546](https://cloud.githubusercontent.com/assets/680073/8304416/42e7a540-19ae-11e5-8314-f67b6ef082b0.png)

Хотя по идее ожидается соответствие стандартам и 

```
<meta charset="utf-8" />
```

Что и где надо поправить?

**Comment by SmetDenis** [comment]
Наконец добрался, подправил в этом коммите https://github.com/smetdenis/jblank/commit/b7858e774a965ab314f28b972b869f2e8ab9e321

Нужно (int) заменить на (bool).
https://github.com/smetdenis/jblank/blob/master/php/libs/template.php#L607

Спасибо!
